# Generated by Django 5.2.6 on 2026-02-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('excerpt', models.TextField(help_text='Short summary shown on the blog listing page.', max_length=500)),
                ('content', models.TextField(help_text='Full blog post content.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Abiral Khatiwada', max_length=100)),
                ('title', models.CharField(default='Flutter Developer | AI Enthusiast', max_length=200)),
                ('bio', models.TextField(default="I'm a passionate Flutter developer and AI enthusiast who loves turning creative ideas into functional apps. My goal is to blend mobile development with artificial intelligence to deliver smarter user experiences.")),
                ('tagline', models.CharField(default='Building intelligent, beautiful, and user-friendly apps that make life easier.', max_length=300)),
                ('email', models.EmailField(default='abiralkhatiwada37@gmail.com', max_length=254)),
                ('github', models.URLField(default='https://github.com/abiralkhatiwada')),
                ('linkedin', models.URLField(default='https://www.linkedin.com/in/abiral-khatiwada-/')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('link', models.URLField(blank=True)),
                ('link_text', models.CharField(default='View Project →', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
