# Generated by Django 5.2.11 on 2026-04-27 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(help_text='e.g. GitHub, LinkedIn, Twitter, Instagram, etc.', max_length=50)),
                ('url', models.URLField()),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='portfolio.profile')),
            ],
            options={
                'ordering': ['order', 'platform'],
            },
        ),
    ]
