# Generated by Django 5.2.11 on 2026-04-27 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_sociallink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='github',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='linkedin',
        ),
    ]
