# Generated by Django 5.2.11 on 2026-05-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_profile_github_remove_profile_linkedin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['category', 'order', 'name']},
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('core', 'Core'), ('backend', 'Backend'), ('database', 'Database'), ('tools', 'Tools'), ('frontend', 'Frontend'), ('advanced', 'Advanced')], default='core', max_length=20),
        ),
    ]
