# Generated by Django 5.2.11 on 2026-05-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_update_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO Meta Description (optional, optimal length: 150-160 characters). If blank, excerpt is used.', max_length=160),
        ),
    ]
