# Generated by Django 4.2.30 on 2026-07-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_blogpost_meta_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlutterApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('excerpt', models.TextField(help_text='Short summary shown on the app listing page.', max_length=500)),
                ('description', models.TextField(help_text='Detailed description of the app.')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='apps/icons/')),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='apps/screenshots/')),
                ('apk_file', models.FileField(help_text='Upload the .apk file here.', upload_to='apps/apks/')),
                ('is_published', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
