# Generated by Django 5.2.11 on 2026-07-22 14:31

import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_flutterapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flutterapp',
            name='apk_file',
            field=models.FileField(help_text='Upload the .apk file here.', storage=portfolio.models.get_apk_storage, upload_to='apps/apks/'),
        ),
    ]
