# Generated by Django 5.2.11 on 2026-07-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_flutterapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flutterapp',
            name='apk_file',
            field=models.URLField(blank=True, help_text='Paste the direct GitHub Release download URL of the APK.'),
        ),
    ]
